### PR TITLE
ci: add example project and basic GitHub actions workflow

### PR DESCRIPTION
**Pull request by mrcjkb**
The CI could be set up with a matrix, but maybe that's too complex for a demo?

### CODE REVIEW

**Comment by mrcjkb** [comment]
Here's a build: https://github.com/mrcjkb/nlua/actions/runs/9293510784/job/25576809129

**Review by mfussenegger — COMMENTED** [review]
Nice to have an example like this, but I have the impression that this would better fit into https://github.com/nvim-lua/nvim-lua-plugin-template - and here we could just add the link to it?

I wanted to migrate the nvim-lua-plugin-template away from plenary busted anyway.

**Comment by mrcjkb** [comment]
I think an example in the plugin template is definitely a good idea. 

The reason I opened this PR is because it includes an "install nlua" step that uses `luarocks make`. That step installs the package from the checked out repo (as opposed to downloading it from luarocks). So the workflow provides some safety against breakage in case of future changes.

**Comment by mfussenegger** [comment]
> I think an example in the plugin template is definitely a good idea.
> 
> The reason I opened this PR is because it includes an "install nlua" step that uses `luarocks make`. That step installs the package from the checked out repo (as opposed to downloading it from luarocks). So the workflow provides some safety against breakage in case of future changes.

Good point about the testing.

I've now created a variant of this in https://github.com/mfussenegger/nlua/pull/9 that doesn't include it as a example project, but rather is just about testing `nlua` itself.

It also links to the plugin template and updates the setup instructions a bit.

Question for you: Can the nlua-scm-1.rockspec and the rockspec.template somehow be merged, or are both required?

**Comment by mrcjkb** [comment]
> Question for you: Can the nlua-scm-1.rockspec and the rockspec.template somehow be merged, or are both required?

luarocks-tag-release populates the rockspec.template with additional repo metadata (description, etc. pulled from github) and sets the source so that luarocks downloads the archive for the release tag.
The scm rockspec is slightly different. 

It might be worth considering a feature in luarocks-tag-release that lets you put a placeholder for the scm rockspec source and then use that to generate the release rockspec. Something like

```lua
local modrev, specrev = 'scm', '1'
version = modrev .. '-' .. specrev
source = "PLACEHOLDER"
if modrev == 'scm' then
  source = ...
end
```

**Pull request closed without merging**
